### ISSUE TITLE
Remove OR fork personal projects from Puppetfile into namesco repo

### ISSUE THREAD

**Issue by flyingbuddha** [namesco/our-boxen#10]
* alexmace/puppet-dnsmasq
* alexmace/puppet-gpgtools

Are both several versions behind their relevant upstreams.

These repos should exist in the namesco repo if they are dependancies of the company setup, as they're unlikely to disappear over time.

**Comment by alexmace** [comment]
Fair enough - first step would be to explore reverting to the default ones, if the underlying issue has been resolved.

**Comment by alexmace** [comment]
1a77d47 has reverted back to the standard dnsmasq

**Comment by alexmace** [comment]
75073b9 has switched to using a namesco fork of gpgtools which does actually work - switched to using a non-SSL URL for downloading GPGTools, because OS X is unable to validate the cert on releases.gpgtools.org
