### ISSUE TITLE
PHP memcached extension failing to install

### ISSUE THREAD

**Issue by alexmace** [namesco/our-boxen#8]
Boxen errors out while trying to install the libmemcached dependency for the PHP memcache extension.

![screen_shot_2015-04-13_at_14 40 20](https://cloud.githubusercontent.com/assets/207391/7123578/0d1416b2-e21b-11e4-826e-c2ca9e95eafe.png)

**Comment by flyingbuddha** [comment]
As noted in chat, I think this is a problem with the libmemcached source. I tried compiling separately last night and experienced similar problems.

Couldn't figure out how to specify a previous version of libmemcached in the puppet task.

**Comment by alexmace** [comment]
This was resolved by https://github.com/Homebrew/homebrew/pull/38735
