### ISSUE TITLE
Remove all files from cache directories in repo

### ISSUE THREAD

**Issue by flyingbuddha** [namesco/our-boxen#9]
I'm a bit conscious of pre-cache bundles being available in the repo in the following locations:
* vendor/cache
* vendor/puppet/cache

I'm concerned that if there are any security holes in these files, they would be replicated to everyone's machine.

I'd like the files to be retrieved on first run of boxen.

I'm aware we're version pegging.

**Comment by alexmace** [comment]
This is the recommended way of using Boxen - when you update something and run boxen, it automatically cleans up the older versions in vendor and adds the new ones, so I don't propose to do anything about this right now.
